
--###################################################################################################################################################################################################################################################################################################################################################################################################################################

INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '1', '0', '0', '12681657', '0', '2', '0', '0', '0', '1', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '1', '15', '0', '12681657', '0', '2', '0', '0', '0', '1', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '1', '30', '0', '12681657', '0', '2', '0', '0', '0', '1', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '1', '45', '0', '12681657', '0', '2', '0', '0', '0', '2', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '2', '0', '0', '12681657', '0', '2', '0', '0', '0', '2', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '2', '15', '0', '12681657', '0', '2', '0', '0', '0', '2', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '2', '30', '0', '12681657', '0', '2', '0', '0', '0', '2', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '2', '45', '0', '12681657', '0', '2', '0', '0', '0', '3', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '3', '0', '0', '12681657', '0', '2', '0', '0', '0', '3', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '3', '15', '0', '12681657', '0', '2', '0', '0', '0', '3', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '3', '30', '0', '12681657', '0', '2', '0', '0', '0', '3', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '3', '45', '0', '12681657', '0', '2', '0', '0', '0', '4', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '4', '0', '0', '12681657', '0', '2', '0', '0', '0', '4', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '4', '15', '0', '12681657', '0', '2', '0', '0', '0', '4', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '4', '30', '0', '12681657', '0', '2', '0', '0', '0', '4', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '4', '45', '0', '12681657', '0', '2', '0', '0', '0', '5', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '5', '0', '0', '12681657', '0', '2', '0', '0', '0', '5', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '5', '15', '0', '12681657', '0', '2', '0', '0', '0', '5', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '5', '30', '0', '12681657', '0', '2', '0', '0', '0', '5', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '5', '45', '0', '12681657', '0', '2', '0', '0', '0', '6', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '6', '0', '0', '12681657', '0', '2', '0', '0', '0', '6', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '6', '15', '0', '12681657', '0', '2', '0', '0', '0', '6', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '6', '30', '0', '12681657', '0', '2', '0', '0', '0', '6', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '6', '45', '0', '12681657', '0', '2', '0', '0', '0', '7', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '7', '0', '0', '12681657', '0', '2', '0', '0', '0', '7', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '7', '15', '0', '12681657', '0', '2', '0', '0', '0', '7', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '7', '30', '0', '12681657', '0', '2', '0', '0', '0', '7', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '7', '45', '0', '12681657', '0', '2', '0', '0', '0', '8', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '8', '0', '0', '12681657', '0', '2', '0', '0', '0', '8', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '8', '15', '0', '12681657', '0', '2', '0', '0', '0', '8', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '8', '30', '0', '12681657', '0', '2', '0', '0', '0', '8', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '8', '45', '0', '12681657', '0', '2', '0', '0', '0', '9', '0', '0');

INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '9', '30', '0', '14516542', '0', '2', '0', '0', '0', '9', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '9', '45', '0', '14516542', '0', '2', '0', '0', '0', '10', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '10', '0', '0', '14516542', '0', '2', '0', '0', '0', '10', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '10', '15', '0', '14516542', '0', '2', '0', '0', '0', '10', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '10', '30', '0', '14516542', '0', '2', '0', '0', '0', '10', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '10', '45', '0', '14516542', '0', '2', '0', '0', '0', '11', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '11', '0', '0', '14516542', '0', '2', '0', '0', '0', '11', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '11', '15', '0', '14516542', '0', '2', '0', '0', '0', '11', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '11', '30', '0', '14516542', '0', '2', '0', '0', '0', '11', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '11', '45', '0', '14516542', '0', '2', '0', '0', '0', '12', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '12', '0', '0', '14516542', '0', '2', '0', '0', '0', '12', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '12', '15', '0', '14516542', '0', '2', '0', '0', '0', '12', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '12', '30', '0', '14516542', '0', '2', '0', '0', '0', '12', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '12', '45', '0', '14516542', '0', '2', '0', '0', '0', '13', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '13', '0', '0', '14516542', '0', '2', '0', '0', '0', '13', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '13', '15', '0', '14516542', '0', '2', '0', '0', '0', '13', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '13', '30', '0', '14516542', '0', '2', '0', '0', '0', '13', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '13', '45', '0', '14516542', '0', '2', '0', '0', '0', '14', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '14', '0', '0', '14516542', '0', '2', '0', '0', '0', '14', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '14', '15', '0', '14516542', '0', '2', '0', '0', '0', '14', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '14', '30', '0', '14516542', '0', '2', '0', '0', '0', '14', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '14', '45', '0', '14516542', '0', '2', '0', '0', '0', '15', '0', '0');

INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '15', '30', '0', '5620090', '0', '2', '0', '0', '0', '15', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '15', '45', '0', '5620090', '0', '2', '0', '0', '0', '16', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '16', '0', '0', '5620090', '0', '2', '0', '0', '0', '16', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '16', '15', '0', '5620090', '0', '2', '0', '0', '0', '16', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '16', '30', '0', '5620090', '0', '2', '0', '0', '0', '16', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '16', '45', '0', '5620090', '0', '2', '0', '0', '0', '17', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '17', '0', '0', '5620090', '0', '2', '0', '0', '0', '17', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '17', '15', '0', '5620090', '0', '2', '0', '0', '0', '17', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '17', '30', '0', '5620090', '0', '2', '0', '0', '0', '17', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '17', '45', '0', '5620090', '0', '2', '0', '0', '0', '18', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '18', '0', '0', '5620090', '0', '2', '0', '0', '0', '18', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '18', '15', '0', '5620090', '0', '2', '0', '0', '0', '18', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '18', '30', '0', '5620090', '0', '2', '0', '0', '0', '18', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '18', '45', '0', '5620090', '0', '2', '0', '0', '0', '19', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '19', '0', '0', '5620090', '0', '2', '0', '0', '0', '19', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '19', '15', '0', '5620090', '0', '2', '0', '0', '0', '19', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '19', '30', '0', '5620090', '0', '2', '0', '0', '0', '19', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '19', '45', '0', '5620090', '0', '2', '0', '0', '0', '20', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '20', '0', '0', '5620090', '0', '2', '0', '0', '0', '20', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '20', '15', '0', '5620090', '0', '2', '0', '0', '0', '20', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '20', '30', '0', '5620090', '0', '2', '0', '0', '0', '20', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '20', '45', '0', '5620090', '0', '2', '0', '0', '0', '21', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '21', '0', '0', '5620090', '0', '2', '0', '0', '0', '21', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '21', '15', '0', '5620090', '0', '2', '0', '0', '0', '21', '30', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '21', '30', '0', '5620090', '0', '2', '0', '0', '0', '21', '45', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '21', '45', '0', '5620090', '0', '2', '0', '0', '0', '22', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '22', '0', '0', '5620090', '0', '2', '0', '0', '0', '22', '15', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_hour', 'M15_', 'High and low of the fifteen minute candle.', '0', '0', '0', '22', '15', '0', '5620090', '0', '2', '0', '0', '0', '22', '30', '0');

--###################################################################################################################################################################################################################################################################################################################################################################################################################################

INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_day', 'session_', 'High and low of the Asian session.', '0', '0', '0', '1', '0', '0', '12681657', '0', '0', '0', '0', '0', '9', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_day', 'session_', 'High and low of the London session.', '0', '0', '0', '9', '30', '0', '14516542', '0', '0', '0', '0', '0', '15', '0', '0');
INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_day', 'session_', 'High and low of the NewYork session.', '0', '0', '0', '15', '30', '0', '5620090', '0', '0', '0', '0', '0', '22', '30', '0');

--###################################################################################################################################################################################################################################################################################################################################################################################################################################

INSERT INTO chart_object('type', 'name', 'description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minutes', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('intra_month', 'weekly_', 'High and low of the week.', '0', '0', '1', '1', '0', '0', '255', '0', '2', '0', '0', '5', '22', '30', '0');
