INSERT INTO months(month) VALUES("January");
INSERT INTO months(month) VALUES("February");
INSERT INTO months(month) VALUES("March");
INSERT INTO months(month) VALUES("April");
INSERT INTO months(month) VALUES("May");
INSERT INTO months(month) VALUES("June");
INSERT INTO months(month) VALUES("July");
INSERT INTO months(month) VALUES("August");
INSERT INTO months(month) VALUES("September");
INSERT INTO months(month) VALUES("October");
INSERT INTO months(month) VALUES("November");
INSERT INTO months(month) VALUES("December");

INSERT INTO daysOfMonth(day) VALUES("dayOfMonthOne");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwo");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthThree");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthFour");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthFive");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthSix");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthSeven");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthEight");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthNine");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTen");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthEleven");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwelve");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthThirteen");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthFourteen");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthFiveteen");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthSixteen");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthSeventeen");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthEighteen");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthNineteen");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwenty");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentyOne");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentyTwo");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentyThree");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentyFour");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentyFive");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentySix");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentySeven");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentyEight");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthTwentyNine");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthThirty");
INSERT INTO daysOfMonth(day) VALUES("dayOfMonthThirtyOne");

INSERT INTO daysOfWeek(day) VALUES("dayOfWeekOne");
INSERT INTO daysOfWeek(day) VALUES("dayOfWeekTwo");
INSERT INTO daysOfWeek(day) VALUES("dayOfWeekThree");
INSERT INTO daysOfWeek(day) VALUES("dayOfWeekFour");
INSERT INTO daysOfWeek(day) VALUES("dayOfWeekFive");

INSERT INTO hoursOfDay(hour) VALUES("hourOfDayOne");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayTwo");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayThree");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayFour");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayFive");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDaySix");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDaySeven");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayEight");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayNine");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayTen");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayEleven");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayTwelve");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayThirteen");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayFourteen");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayFiveteen");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDaySixteen");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDaySeventeen");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayEighteen");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayNineteen");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayTwenty");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayTwentyOne");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayTwentyTwo");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayTwentyThree");
INSERT INTO hoursOfDay(hour) VALUES("hourOfDayTwentyFour");

INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourOne");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwo");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThree");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFour");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFive");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourSix");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourSeven");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourEight");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourNine");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTen");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourEleven");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwelve");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirteen");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourteen");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFiveteen");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourSixteen");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourSeventeen");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourEighteen");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourNineteen");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwenty");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentyOne");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentyTwo");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentyThree");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentyFour");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentyFive");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentySix");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentySeven");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentyEight");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourTwentyNine");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirty");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtyOne");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtyTwo");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtyThree");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtyFour");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtyFive");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtySix");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtySeven");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtyEight");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourThirtyNine");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourty");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtyOne");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtyTwo");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtyThree");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtyFour");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtyFive");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtySix");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtySeven");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtyEight");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFourtyNine");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivety");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetyOne");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetyTwo");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetyThree");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetyFour");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetyFive");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetySix");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetySeven");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetyEight");
INSERT INTO minutesOfHour(minute) VALUES("minuteOfHourFivetyNine");

INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('session_', '0', '0', '0', '3', '0', '0', '12681657', '0', '0', '0', '0', '0', '7', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('session_', '0', '0', '0', '7', '0', '0', '14516542', '0', '0', '0', '0', '0', '11', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('session_', '0', '0', '0', '11', '0', '0', '5620090', '0', '0', '0', '0', '0', '15', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('session_', '0', '0', '0', '15', '0', '0', '3093151', '0', '0', '0', '0', '0', '19', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('day_', '0', '0', '0', '2', '0', '0', '0', '0', '4', '0', '0', '0', '23', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_a_', '0', '0', '0', '3', '0', '0', '12681657', '0', '2', '0', '0', '0', '3', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_b_', '0', '0', '0', '3', '15', '0', '12681657', '0', '2', '0', '0', '0', '3', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_c_', '0', '0', '0', '3', '30', '0', '12681657', '0', '2', '0', '0', '0', '3', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_d_', '0', '0', '0', '3', '45', '0', '12681657', '0', '2', '0', '0', '0', '4', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_e_', '0', '0', '0', '4', '0', '0', '12681657', '0', '2', '0', '0', '0', '4', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_f_', '0', '0', '0', '4', '15', '0', '12681657', '0', '2', '0', '0', '0', '4', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_g_', '0', '0', '0', '4', '30', '0', '12681657', '0', '2', '0', '0', '0', '4', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_h_', '0', '0', '0', '4', '45', '0', '12681657', '0', '2', '0', '0', '0', '5', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_i_', '0', '0', '0', '5', '0', '0', '12681657', '0', '2', '0', '0', '0', '5', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_j_', '0', '0', '0', '5', '15', '0', '12681657', '0', '2', '0', '0', '0', '5', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_k_', '0', '0', '0', '5', '30', '0', '12681657', '0', '2', '0', '0', '0', '5', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_l_', '0', '0', '0', '5', '45', '0', '12681657', '0', '2', '0', '0', '0', '6', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_m_', '0', '0', '0', '6', '0', '0', '12681657', '0', '2', '0', '0', '0', '6', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_n_', '0', '0', '0', '6', '15', '0', '12681657', '0', '2', '0', '0', '0', '6', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_o_', '0', '0', '0', '6', '30', '0', '12681657', '0', '2', '0', '0', '0', '6', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_p_', '0', '0', '0', '6', '45', '0', '12681657', '0', '2', '0', '0', '0', '7', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_q_', '0', '0', '0', '7', '0', '0', '14516542', '0', '2', '0', '0', '0', '7', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_r_', '0', '0', '0', '7', '15', '0', '14516542', '0', '2', '0', '0', '0', '7', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_s_', '0', '0', '0', '7', '30', '0', '14516542', '0', '2', '0', '0', '0', '7', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_t_', '0', '0', '0', '7', '45', '0', '14516542', '0', '2', '0', '0', '0', '8', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_u_', '0', '0', '0', '8', '0', '0', '14516542', '0', '2', '0', '0', '0', '8', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_v_', '0', '0', '0', '8', '15', '0', '14516542', '0', '2', '0', '0', '0', '8', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_w_', '0', '0', '0', '8', '30', '0', '14516542', '0', '2', '0', '0', '0', '8', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_x_', '0', '0', '0', '8', '45', '0', '14516542', '0', '2', '0', '0', '0', '9', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_y_', '0', '0', '0', '9', '0', '0', '14516542', '0', '2', '0', '0', '0', '9', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_z_', '0', '0', '0', '9', '15', '0', '14516542', '0', '2', '0', '0', '0', '9', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aa_', '0', '0', '0', '9', '30', '0', '14516542', '0', '2', '0', '0', '0', '9', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ab_', '0', '0', '0', '9', '45', '0', '14516542', '0', '2', '0', '0', '0', '10', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ac_', '0', '0', '0', '10', '0', '0', '14516542', '0', '2', '0', '0', '0', '10', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ad_', '0', '0', '0', '10', '15', '0', '14516542', '0', '2', '0', '0', '0', '10', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ae_', '0', '0', '0', '10', '30', '0', '14516542', '0', '2', '0', '0', '0', '10', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_af_', '0', '0', '0', '10', '45', '0', '14516542', '0', '2', '0', '0', '0', '11', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ag_', '0', '0', '0', '11', '0', '0', '5620090', '0', '2', '0', '0', '0', '11', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ah_', '0', '0', '0', '11', '15', '0', '5620090', '0', '2', '0', '0', '0', '11', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ai_', '0', '0', '0', '11', '30', '0', '5620090', '0', '2', '0', '0', '0', '11', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aj_', '0', '0', '0', '11', '45', '0', '5620090', '0', '2', '0', '0', '0', '12', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ak_', '0', '0', '0', '12', '0', '0', '5620090', '0', '2', '0', '0', '0', '12', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_al_', '0', '0', '0', '12', '15', '0', '5620090', '0', '2', '0', '0', '0', '12', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_am_', '0', '0', '0', '12', '30', '0', '5620090', '0', '2', '0', '0', '0', '12', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_an_', '0', '0', '0', '12', '45', '0', '5620090', '0', '2', '0', '0', '0', '13', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ao_', '0', '0', '0', '13', '0', '0', '5620090', '0', '2', '0', '0', '0', '13', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ap_', '0', '0', '0', '13', '15', '0', '5620090', '0', '2', '0', '0', '0', '13', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aq_', '0', '0', '0', '13', '30', '0', '5620090', '0', '2', '0', '0', '0', '13', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ar_', '0', '0', '0', '13', '45', '0', '5620090', '0', '2', '0', '0', '0', '14', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_as_', '0', '0', '0', '14', '0', '0', '5620090', '0', '2', '0', '0', '0', '14', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_at_', '0', '0', '0', '14', '15', '0', '5620090', '0', '2', '0', '0', '0', '14', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_au_', '0', '0', '0', '14', '30', '0', '5620090', '0', '2', '0', '0', '0', '14', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_av_', '0', '0', '0', '14', '45', '0', '5620090', '0', '2', '0', '0', '0', '15', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aw_', '0', '0', '0', '15', '0', '0', '3093151', '0', '2', '0', '0', '0', '15', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ax_', '0', '0', '0', '15', '15', '0', '3093151', '0', '2', '0', '0', '0', '15', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_ay_', '0', '0', '0', '15', '30', '0', '3093151', '0', '2', '0', '0', '0', '15', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_az_', '0', '0', '0', '15', '45', '0', '3093151', '0', '2', '0', '0', '0', '16', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aaa_', '0', '0', '0', '16', '0', '0', '3093151', '0', '2', '0', '0', '0', '16', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aab_', '0', '0', '0', '16', '15', '0', '3093151', '0', '2', '0', '0', '0', '16', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aac_', '0', '0', '0', '16', '30', '0', '3093151', '0', '2', '0', '0', '0', '16', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aad_', '0', '0', '0', '16', '45', '0', '3093151', '0', '2', '0', '0', '0', '17', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aae_', '0', '0', '0', '17', '0', '0', '3093151', '0', '2', '0', '0', '0', '17', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aaf_', '0', '0', '0', '17', '15', '0', '3093151', '0', '2', '0', '0', '0', '17', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aag_', '0', '0', '0', '17', '30', '0', '3093151', '0', '2', '0', '0', '0', '17', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aah_', '0', '0', '0', '17', '45', '0', '3093151', '0', '2', '0', '0', '0', '18', '0', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aai_', '0', '0', '0', '18', '0', '0', '3093151', '0', '2', '0', '0', '0', '18', '15', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aaj_', '0', '0', '0', '18', '15', '0', '3093151', '0', '2', '0', '0', '0', '18', '30', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aak_', '0', '0', '0', '18', '30', '0', '3093151', '0', '2', '0', '0', '0', '18', '45', '0');
INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_aal_', '0', '0', '0', '18', '45', '0', '3093151', '0', '2', '0', '0', '0', '19', '0', '0');

--##############################################################################################################################################################################################################################################################################################################################################################

INSERT INTO perimeter('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds') VALUES('fifteen_minute_tester_', '0', '0', '0', '19', '0', '0', '3093151', '0', '2', '0', '0', '0', '19', '15', '0');
