
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('session', '0', '0', '0', '3', '0', '0', '15453831', '1', '0', '0', '0', '0', '7', '0', '0', 'true', 'true', 'true', 'true', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('session', '0', '0', '0', '7', '0', '0', '2723621', '1', '0', '0', '0', '0', '11', '0', '0', 'true', 'true', 'true', 'true', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('session', '0', '0', '0', '11', '0', '0', '11823615', '1', '0', '0', '0', '0', '15', '0', '0', 'true', 'true', 'true', 'true', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('session', '0', '0', '0', '15', '0', '0', '3093151', '1', '0', '0', '0', '0', '19', '0', '0', 'true', 'true', 'true', 'true', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('session', '0', '0', '0', '19', '0', '0', '8421376', '1', '0', '0', '0', '0', '23', '0', '0', 'true', 'true', 'true', 'true', 'false', 'false', 'false', 'false', 'false');

INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_a', '0', '0', '0', '3', '0', '0', '14053594', '0', '2', '0', '0', '0', '4', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_b', '0', '0', '0', '4', '0', '0', '14053594', '0', '2', '0', '0', '0', '5', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_c', '0', '0', '0', '5', '0', '0', '14053594', '0', '2', '0', '0', '0', '6', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_d', '0', '0', '0', '6', '0', '0', '14053594', '0', '2', '0', '0', '0', '7', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_e', '0', '0', '0', '7', '0', '0', '1323384', '0', '2', '0', '0', '0', '8', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_f', '0', '0', '0', '8', '0', '0', '1323384', '0', '2', '0', '0', '0', '9', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_g', '0', '0', '0', '9', '0', '0', '1323384', '0', '2', '0', '0', '0', '10', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_h', '0', '0', '0', '10', '0', '0', '1323384', '0', '2', '0', '0', '0', '11', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_i', '0', '0', '0', '11', '0', '0', '4953600', '0', '2', '0', '0', '0', '12', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_j', '0', '0', '0', '12', '0', '0', '4953600', '0', '2', '0', '0', '0', '13', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_k', '0', '0', '0', '13', '0', '0', '4953600', '0', '2', '0', '0', '0', '14', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_l', '0', '0', '0', '14', '0', '0', '4953600', '0', '2', '0', '0', '0', '15', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_m', '0', '0', '0', '15', '0', '0', '16734720', '0', '2', '0', '0', '0', '16', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_n', '0', '0', '0', '16', '0', '0', '16734720', '0', '2', '0', '0', '0', '17', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_o', '0', '0', '0', '17', '0', '0', '16734720', '0', '2', '0', '0', '0', '18', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_p', '0', '0', '0', '18', '0', '0', '16734720', '0', '2', '0', '0', '0', '19', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_q', '0', '0', '0', '19', '0', '0', '8355839', '0', '2', '0', '0', '0', '20', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_r', '0', '0', '0', '20', '0', '0', '8355839', '0', '2', '0', '0', '0', '21', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_t', '0', '0', '0', '21', '0', '0', '8355839', '0', '2', '0', '0', '0', '22', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('hour_u', '0', '0', '0', '22', '0', '0', '8355839', '0', '2', '0', '0', '0', '23', '0', '0', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false');

INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('daily_high', '0', '0', '1', '1', '0', '0', '8355839', '0', '2', '0', '0', '1', '23', '30', '0', 'true', 'true', 'true', 'true', 'false', 'false', 'false', 'false', 'false');
INSERT INTO component('description', 'start_month', 'start_week', 'start_day', 'start_hour', 'start_minute', 'start_seconds', 'clr', 'width', 'style', 'end_month', 'end_week', 'end_day', 'end_hour', 'end_minute', 'end_seconds', 'show_m1', 'show_m5', 'show_m15', 'show_m30', 'show_h1', 'show_h4', 'show_d1', 'show_w1', 'show_mn1') VALUES('daily_low', '0', '0', '1', '1', '0', '0', '8355839', '0', '2', '0', '0', '1', '23', '30', '0', 'true', 'true', 'true', 'true', 'false', 'false', 'false', 'false', 'false');